# Generated by Django 6.1 on 2026-08-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='user',
            new_name='owner',
        ),
    ]
