# Generated by Django 6.1 on 2026-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_rename_user_warehouse_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300)),
                ('place_id', models.IntegerField()),
                ('type', models.CharField()),
                ('normalized_address', models.SlugField(blank=True, max_length=300)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
            ],
        ),
    ]
